name: two-photon
channels:
  - conda-forge
  - defaults
  - pytorch
  - numba

dependencies:
  - python>=3.8,<3.9
  - pip
  - dask
  - yapf
  - jupyterlab
  - mkl
  - tbb
  - numpy
  - numba
  - matplotlib
  - scipy>=1.4.0
  - scikit-learn
  - h5py=2.10.0
  - scikit-image
  - pandas
  - pytables
  - mkl_fft
  - pip:
    - pyqt5
    - pyqt5.sip
    - pyqt5-tools
    - torch>=1.7.1
    - natsort
    - rastermap>0.1.0
    - tifffile
    - scanimage-tiff-reader>=1.4.1
    - pyqtgraph
    - importlib-metadata
    - paramiko
    - pynwb
    - sbxreader
    - cellpose