name: two-photon
channels:
  - conda-forge
  - defaults
dependencies:
  - dask
  - tbb
  - numpy<1.19.0
  - pandas
  - pip
  - pytables
  - python>=3.7.6,<3.8
  - scipy
  - yapf
  - jupyterlab
  - mkl_fft=1.0.10
  - mkl=2019.3
  - numba<0.50.0
  - matplotlib
  - scipy
  - scikit-learn
  - pyqt
  - scikit-image
     
  - pip:
    - h5py==2.10.0
    - natsort
    - rastermap>0.1.0
    - tifffile==2020.7.22
    - scanimage-tiff-reader>=1.4.1
    - pyqtgraph
    - importlib-metadata
    - paramiko
    - pynwb
    - sbxreader
    - suite2p==0.10.0