channels:
  - conda-forge
  - defaults
dependencies:
  - dask=2.11
  - h5py=2.10
  - numpy=1.16
  - pandas=1.0
  - pip=20.0
  - pytables=3.6
  - pytest=6.0
  - python=3.6
  - rope=0.17
  - scikit-image=0.16
  - tifffile=2020.2.16
  - yapf
  - pip:
    - suite2p==0.7.1
